package br.com.academia2.model;
// Generated 19/07/2019 12:01:09 by Hibernate Tools 4.3.1



/**
 * Modeloabdome generated by hbm2java
 */
public class Modeloabdome  implements java.io.Serializable {


     private Integer id;
     private int idabdome;
     private String divt;
     private int serie;
     private int rept;
     private int carga;
     private int intponto;
     private String cadencia;

    public Modeloabdome() {
    }

    public Modeloabdome(int idabdome, String divt, int serie, int rept, int carga, int intponto, String cadencia) {
       this.idabdome = idabdome;
       this.divt = divt;
       this.serie = serie;
       this.rept = rept;
       this.carga = carga;
       this.intponto = intponto;
       this.cadencia = cadencia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdabdome() {
        return this.idabdome;
    }
    
    public void setIdabdome(int idabdome) {
        this.idabdome = idabdome;
    }
    public String getDivt() {
        return this.divt;
    }
    
    public void setDivt(String divt) {
        this.divt = divt;
    }
    public int getSerie() {
        return this.serie;
    }
    
    public void setSerie(int serie) {
        this.serie = serie;
    }
    public int getRept() {
        return this.rept;
    }
    
    public void setRept(int rept) {
        this.rept = rept;
    }
    public int getCarga() {
        return this.carga;
    }
    
    public void setCarga(int carga) {
        this.carga = carga;
    }
    public int getIntponto() {
        return this.intponto;
    }
    
    public void setIntponto(int intponto) {
        this.intponto = intponto;
    }
    public String getCadencia() {
        return this.cadencia;
    }
    
    public void setCadencia(String cadencia) {
        this.cadencia = cadencia;
    }




}


