/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.academia2.viewr.cliente;

import academia2.GeraMatricula;
import academia2.HibernateUtil;
import academia2.ValidadorCpf;
import br.com.academia2.model.Cliente;
import br.com.academia2.model.Mensalidade;
import br.com.academia2.viewr.mensalidade.ClienteMesesAbertos;
import java.awt.Color;
import java.io.Serializable;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Antonio Rony
 */
public class GerenciaCliente extends javax.swing.JDialog {
    private DefaultTableModel tmResultSet = new DefaultTableModel(null, new String[]{"ID", "NOME", "APELIDO", "CPF", "TELEFONE", "LOGRADOURO", "NÚMERO","BAIRRO","CIDADE","ESTADO","NASCIMENTO", "MATRICULA"});
    ;
  java.util.List<br.com.academia2.model.Cliente> resultado;
    private ListSelectionModel lsmResult;
    private DefaultTableModel tabela;
    private int idDescricaoControle;
    /**
     * Creates new form GestaoCliente
     */
    public GerenciaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTApelido = new javax.swing.JTextField();
        jFCPF = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTelefone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTLogradouro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JComboBox<>();
        jTMunicipio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);          lsmResult = jTable1.getSelectionModel();          lsmResult.addListSelectionListener(new ListSelectionListener() {               public void valueChanged(ListSelectionEvent e) {                                        if (! e.getValueIsAdjusting()){                           jTTabelaLinhaSelecionada(jTable1);                       }                                    }          });
        jButton4 = new javax.swing.JButton();
        jTPesq = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBFicha = new javax.swing.JButton();
        jBFicha.setBackground(new Color(0,0,0,1));
        jButton1 = new javax.swing.JButton();
        jButton1.setBackground(new Color(0,0,0,1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(678, 473));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APELIDO");

        jTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTNomeKeyPressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOME");

        try {
            jFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFCPFKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");

        try {
            jFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTelefoneKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELEFONE:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA NASC.");

        try {
            jFDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFDataNascimentoKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOGRADOURO: ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("N°");

        jTNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumeroKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BAIRRO:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UF");

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MUNICIPIO:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NÚMERO MATRICULA:");

        jTMatricula.setEditable(false);
        jTMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMatriculaKeyTyped(evt);
            }
        });

        jTable1.setModel(tmResultSet);
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new Color(0,0,0,1));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/pesquisa.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesqActionPerformed(evt);
            }
        });

        jBAdicionar.setBackground(new Color(0,0,0,1));
        jBAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/add_icon.png"))); // NOI18N
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new Color(0,0,0,1));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/EDITAR.png"))); // NOI18N
        jBEditar.setPreferredSize(new java.awt.Dimension(65, 35));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setBackground(new Color(0,0,0,1));
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/remove.png"))); // NOI18N
        jBExcluir.setPreferredSize(new java.awt.Dimension(65, 36));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBFicha.setForeground(new java.awt.Color(240, 240, 240));
        jBFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/FICHA.png"))); // NOI18N
        jBFicha.setText("FICHA");
        jBFicha.setEnabled(false);
        jBFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFichaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/DINDIN.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTApelido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFTelefone)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTLogradouro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTBairro)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 30, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jBFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTPesq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFicha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(724, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
    ValidadorCpf valida = new ValidadorCpf();
    valida.validaCpf(jFCPF.getText());
        if (valida.retorno()) {
            salvar();
        }else{
            JOptionPane.showMessageDialog(this, "CPF INVALIDO, Verifique-o");
        }
       
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Realmente Deseja ALTERAR");
        if (confirm == 0) {
            editar();
        }else{
            
        }
                // TODO add your handling code here:;
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Realmente Deseja EXCLUIR");
        if (confirm == 0) {
            excluir();
        }else{
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesqActionPerformed

    private void jTNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumeroKeyTyped
String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroKeyTyped

    private void jFDataNascimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFDataNascimentoKeyTyped
String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
}         // TODO add your handling code here:
    }//GEN-LAST:event_jFDataNascimentoKeyTyped

    private void jFTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTelefoneKeyTyped
String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
}         // TODO add your handling code here:
    }//GEN-LAST:event_jFTelefoneKeyTyped

    private void jFCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFCPFKeyTyped
String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
}         // TODO add your handling code here:
    }//GEN-LAST:event_jFCPFKeyTyped

    private void jTMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMatriculaKeyTyped

         // TODO add your handling code here:
    }//GEN-LAST:event_jTMatriculaKeyTyped

    private void jTNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomeKeyPressed
       GeraMatricula geraMatricula = new GeraMatricula();
       geraMatricula.pegaData();
       String matriculaNum = geraMatricula.matriculaGerada();
       jTMatricula.setText(matriculaNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeKeyPressed

    private void jBFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFichaActionPerformed
      GerenciaFicha ficha =  new GerenciaFicha(null, true);
      ficha.setaValoresCliente(idDescricaoControle, jTNome.getText(), jTMatricula.getText());
      ficha.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFichaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClienteMesesAbertos abertos = new ClienteMesesAbertos(null, true);
        abertos.recebeId(this.idDescricaoControle);
        abertos.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciaCliente dialog = new GerenciaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBFicha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCEstado;
    private javax.swing.JFormattedTextField jFCPF;
    private javax.swing.JFormattedTextField jFDataNascimento;
    private javax.swing.JFormattedTextField jFTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApelido;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTLogradouro;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JTextField jTMunicipio;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTPesq;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void salvar(){
        Cliente cliente = new Cliente();
        cliente.setNome(jTNome.getText());
        cliente.setApelido(jTApelido.getText());
        cliente.setCpf(jFCPF.getText());
        cliente.setTelefone(jFTelefone.getText());
        cliente.setDataNascimento(jFDataNascimento.getText());
        cliente.setLogradouro(jTLogradouro.getText());
        cliente.setNumero(Integer.parseInt(jTNumero.getText()));
        cliente.setEstado(jCEstado.getSelectedItem().toString());
        cliente.setBairro(jTBairro.getText());
        cliente.setCidade(jTMunicipio.getText());
        cliente.setIdMatricula(jTMatricula.getText());
        
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Serializable idGerado = session.save(cliente);
        session.getTransaction().commit();
        //cadastra a mensalidade do cliente.
        cadastroMensalidade((int) idGerado);
        
        JOptionPane.showMessageDialog(this, "Cadastrado com Sucesso.");
        limparCampos();
        buscar();
        
    }
 private void buscar() {
        tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        //PESQUISA COM SQLQUERY E JOIN MAIS TRANSFORMACAO EM LISTA DO HIBERNATE.
        SQLQuery query;
        if(jTPesq.getText().equals("")||jTPesq.getText().equals(" ")){
            query = sesion.createSQLQuery("SELECT*FROM cliente");
            query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
        }else{
            String nome = jTNome.getText();
            query = sesion.createSQLQuery("SELECT*FROM cliente where nome LIKE '%"+nome+"%' ");
            query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
        }
        
        java.util.List results = query.list();
        for (Object object : results) {
            Map row = (Map) object;
            tmResultSet.addRow(new Object[]{
                row.get("id"),
                row.get("nome"),
                row.get("apelido"),
                row.get("cpf"),
                row.get("telefone"),
                row.get("logradouro"),
                row.get("numero"),
                row.get("bairro"),
                row.get("cidade"),
                row.get("estado"),
                row.get("dataNascimento"),
                row.get("idMatricula")
                //row.get("carga")
            });
        }
                jBAdicionar.setEnabled(true);

    }   
 
    private void jTTabelaLinhaSelecionada(JTable tabela) {
        if (jTable1.getSelectedRow() != -1) {
            String cod = (jTable1.getValueAt(jTable1.getSelectedRow(), 0)).toString();
            this.idDescricaoControle = Integer.parseInt(cod);
            jTNome.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 1)).toString());
            jTApelido.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 2)).toString());
            jFCPF.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 3)).toString());
            jFTelefone.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 4)).toString());
            jTLogradouro.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 5)).toString());
            jTNumero.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jTBairro.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jTMunicipio.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jCEstado.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            jFDataNascimento.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
            jTMatricula.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
            // jTMarca.setText(nomeMarca);
            jBAdicionar.setEnabled(false);
            habilita();
            //System.out.println(this.idDescricaoControle);
        }

    }

    private void editar() {
        Cliente cliente = new Cliente();
        cliente.setId(this.idDescricaoControle);
        cliente.setNome(jTNome.getText());
        cliente.setApelido(jTApelido.getText());
        cliente.setCpf(jFCPF.getText());
        cliente.setTelefone(jFTelefone.getText());
        cliente.setDataNascimento(jFDataNascimento.getText());
        cliente.setLogradouro(jTLogradouro.getText());
        cliente.setNumero(Integer.parseInt(jTNumero.getText()));
        cliente.setEstado(jCEstado.getSelectedItem().toString());
        cliente.setBairro(jTBairro.getText());
        cliente.setCidade(jTMunicipio.getText());
        cliente.setIdMatricula(jTMatricula.getText());
        
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.update(cliente);
        session.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Alterado Com Sucesso.");
        buscar();
        limparCampos();
        desabilita();
        jBAdicionar.setEnabled(true);
    }

    private void excluir() {
        Cliente cliente = new Cliente();
        cliente.setId(this.idDescricaoControle);
        cliente.setNome(jTNome.getText());
        cliente.setApelido(jTApelido.getText());
        cliente.setCpf(jFCPF.getText());
        cliente.setTelefone(jFTelefone.getText());
        cliente.setDataNascimento(jFDataNascimento.getText());
        cliente.setLogradouro(jTLogradouro.getText());
        cliente.setNumero(Integer.parseInt(jTNumero.getText()));
        cliente.setEstado(jCEstado.getSelectedItem().toString());
        cliente.setBairro(jTBairro.getText());
        cliente.setCidade(jTMunicipio.getText());
        cliente.setIdMatricula(jTMatricula.getText());
        
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.delete(cliente);
        session.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Excluido Com Sucesso.");
        buscar();    
        limparCampos();
        desabilita();
        jBAdicionar.setEnabled(true);
    }
    public void limparCampos(){
        jTApelido.setText("");
        jTBairro.setText("");
        jTLogradouro.setText("");
        jTMatricula.setText("");
        jTNome.setText("");
        jTNumero.setText("");
        jTPesq.setText("");
        jFCPF.setText("");
        jFDataNascimento.setText("");
        jFTelefone.setText("");
    }
    public void desabilita(){
        jBEditar.setEnabled(false);
        jBExcluir.setEnabled(false);
        jBFicha.setEnabled(false);
    }
    public void habilita(){
        jBEditar.setEnabled(true);
        jBExcluir.setEnabled(true);        
        jBFicha.setEnabled(true);
    }

    //cadastro preliminar da mensalidade
    private void cadastroMensalidade(int idGerado) {
        
        int jan = 1;
        int fer = 2;
        int mar = 3;
        int abr = 4;
        int mai = 5;
        int jun = 6;
        int jul = 7;
        int ago = 8;
        int setb = 9;
        int outb = 10;
        int nov = 11;
        int dez = 12;
        Mensalidade ms = new Mensalidade();
        GeraMatricula gr = new GeraMatricula();
        gr.pegaData();
        if((gr.getNumeroMes()+1)==jan){
           
        }else if((gr.getNumeroMes()+1)==fer){
            ms.setJaneriro("pago");
        }else if((gr.getNumeroMes()+1)==mar){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
        }else if((gr.getNumeroMes()+1)==abr){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
        }else if((gr.getNumeroMes()+1)==mai){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");

        }else if((gr.getNumeroMes()+1)==jun){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
        }else if((gr.getNumeroMes()+1)==jul){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
            ms.setJunho("pago");
        }else if((gr.getNumeroMes()+1)==ago){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
            ms.setJunho("pago");
            ms.setJulho("pago");
            
        }else if((gr.getNumeroMes()+1)==setb){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
            ms.setJunho("pago");
            ms.setJulho("pago");
            ms.setAgosto("pago");
        }else if((gr.getNumeroMes()+1)==outb){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
            ms.setJunho("pago");
            ms.setJulho("pago");
            ms.setAgosto("pago");
            ms.setSetembro("pago");
        }else if((gr.getNumeroMes()+1)==nov){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
            ms.setJunho("pago");
            ms.setJulho("pago");
            ms.setAgosto("pago");
            ms.setSetembro("pago");
            ms.setOutubro("pago");
        }else if((gr.getNumeroMes()+1)==dez){
            ms.setJaneriro("pago");
            ms.setFevereiro("pago");
            ms.setMarco("pago");
            ms.setAbril("pago");
            ms.setMaio("pago");
            ms.setJunho("pago");
            ms.setJulho("pago");
            ms.setAgosto("pago");
            ms.setSetembro("pago");
            ms.setOutubro("pago");
            ms.setNovembro("pago");
        }
        
        
        ms.setIdCliente(idGerado);
        ms.setValor(50);
        GeraMatricula gera = new GeraMatricula();
        gera.pegaData();
        ms.setAno(String.valueOf(gera.getNumeroAno()));
        //System.out.println(idGerado+"|"+gera.getNumeroAno());
        
        Session ses = HibernateUtil.getSessionFactory().openSession();
        ses.beginTransaction();
        ses.save(ms);
        ses.getTransaction().commit();
        
        System.out.println("Salvo");
        
    }
}
