/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.academia2.viewr.cliente;

import academia2.HibernateUtil;
import br.com.academia2.model.Ficha;
import java.awt.Color;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Hibernate;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Antonio Rony
 */
public class GerenciaFicha extends javax.swing.JDialog {
    private DefaultTableModel tmResultSet = new DefaultTableModel(null, new String[]{"ID", "MATRICULA", "DATA ENTRADA", "SEXO", "PESO", "ALTURA", "IDADE","FREQ. CARD.","FREQ. CARD. MAX.","BATIMENTOS","PROB. SAUDE", "MEDICAÇÃO", "ACOMP.", "OBJ.","PROF.","MODELO","CLIENTE"});
    ;
  java.util.List<br.com.academia2.model.Ficha> resultado;
    private ListSelectionModel lsmResult;
    private DefaultTableModel tabela;
    private int idDescricaoControle;
    /**
     * Creates new form GerenciaFicha
     */
    public GerenciaFicha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pegaFicha();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFDataEntrada = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFreqCard = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTPeso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFreqCardM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCSexo = new javax.swing.JComboBox<>();
        jTIdade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTAltura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);          lsmResult = jTable1.getSelectionModel();          lsmResult.addListSelectionListener(new ListSelectionListener() {               public void valueChanged(ListSelectionEvent e) {                                        if (! e.getValueIsAdjusting()){                           jTTabelaLinhaSelecionada(jTable1);                       }                                    }          });
        jButton4 = new javax.swing.JButton();
        jTPesq = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLId = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTBatimentos = new javax.swing.JTextField();
        jCProbSaude = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTMedicacao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jCAcompanhamento = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTObjetivo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTProfissao = new javax.swing.JTextField();
        jLCliente = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCModeloFicha = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton1.setBackground(new Color(0,0,0,1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MATRICULA");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOME");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA ENTRADA");

        try {
            jFDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FREQ. CARDIACA");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PESO");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BATIMENTOS");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SEXO");

        jCSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PROB. SAUDE");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ALTURA");

        jTable1.setModel(tmResultSet);
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new Color(0,0,0,1));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/pesquisa.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBAdicionar.setBackground(new Color(0,0,0,1));
        jBAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/add_icon.png"))); // NOI18N
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new Color(0,0,0,1));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/EDITAR.png"))); // NOI18N
        jBEditar.setPreferredSize(new java.awt.Dimension(65, 35));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setBackground(new Color(0,0,0,1));
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/remove.png"))); // NOI18N
        jBExcluir.setPreferredSize(new java.awt.Dimension(65, 36));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COD.");

        jLId.setForeground(new java.awt.Color(255, 255, 255));
        jLId.setText("1");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("IDADE");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FREQ. CARDIACA MAX.");

        jCProbSaude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NAO" }));
        jCProbSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProbSaudeActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MEDICAÇÃO");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ACOMPANHAMENTO");

        jCAcompanhamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NAO" }));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("OBJETIVO");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("PROFISSAO");

        jLCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLCliente.setText("NOME COMPLETO DO CLIENTE");

        jLMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLMatricula.setText("12346567890");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID Ficha");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MODELO FICHA:");

        jCModeloFicha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));
        jCModeloFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCModeloFichaActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/academia2/icone/busq.png"))); // NOI18N
        jButton1.setText("VISUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLId)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFreqCard, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTFreqCardM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTMedicacao)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTBatimentos)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTIdade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCProbSaude, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCAcompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTProfissao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTPesq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(32, 32, 32)
                        .addComponent(jCModeloFicha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(jLId)
                    .addComponent(jLCliente)
                    .addComponent(jLMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFreqCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTFreqCardM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTBatimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jCProbSaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMedicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jCAcompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jButton1)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCModeloFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        adicionar();
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        int confirma = JOptionPane.showConfirmDialog(this, "Realmente Deseja Editar?");
        if (confirma == 0) {
            editar();            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(this, "Realmente Deseja Excluir?");
        if (confirma == 0) {
            excluir();            
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jCProbSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProbSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCProbSaudeActionPerformed

    private void jCModeloFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCModeloFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCModeloFichaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       GerenciaModeloFicha gmf = new GerenciaModeloFicha(null, true);
       int idmf = Integer.parseInt(jCModeloFicha.getSelectedItem().toString());
       gmf.buscarId(idmf);
       gmf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciaFicha dialog = new GerenciaFicha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCAcompanhamento;
    private javax.swing.JComboBox<String> jCModeloFicha;
    private javax.swing.JComboBox<String> jCProbSaude;
    private javax.swing.JComboBox<String> jCSexo;
    private javax.swing.JFormattedTextField jFDataEntrada;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTBatimentos;
    private javax.swing.JTextField jTFreqCard;
    private javax.swing.JTextField jTFreqCardM;
    private javax.swing.JTextField jTIdade;
    private javax.swing.JTextField jTMedicacao;
    private javax.swing.JTextField jTObjetivo;
    private javax.swing.JTextField jTPeso;
    private javax.swing.JTextField jTPesq;
    private javax.swing.JTextField jTProfissao;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void setaValoresCliente(int id, String nome, String matricula) {
        jLId.setText(String.valueOf(id));
        jLCliente.setText(nome);
        jLMatricula.setText(matricula);
    }

    public void adicionar() {
        Ficha ficha = new Ficha();
        ficha.setIdCliente(Integer.parseInt(jLId.getText()));
        ficha.setAcompanhamento(jCAcompanhamento.getSelectedItem().toString());
        ficha.setAltura(Float.parseFloat(jTAltura.getText()));
        ficha.setBatimentos(jTBatimentos.getText());
        ficha.setDataEntrada(jFDataEntrada.getText());
        ficha.setFrequenciaCardMaxima(Float.parseFloat(jTFreqCardM.getText()));
        ficha.setFrequenciaCardiaca(Float.parseFloat(jTFreqCard.getText()));
        ficha.setIdModeloFicha(Integer.parseInt(jCModeloFicha.getSelectedItem().toString()));
        ficha.setIdade(Integer.parseInt(jTIdade.getText()));
        ficha.setMatricula(jLMatricula.getText());
        ficha.setMedicacao(jTMedicacao.getText());
        ficha.setObjetivo(jTObjetivo.getText());
        ficha.setPeso(Float.parseFloat(jTPeso.getText()));
        ficha.setProblemaSaude(jCProbSaude.getSelectedItem().toString());
        ficha.setProfissao(jTProfissao.getText());
        ficha.setSexo(jCSexo.getSelectedItem().toString());

        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.save(ficha);
        session.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Salvo Com Sucesso.");

    }

    public void buscar() {
        tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        //PESQUISA COM SQLQUERY E JOIN MAIS TRANSFORMACAO EM LISTA DO HIBERNATE.
        SQLQuery query;
        if (jLId.getText().equals("") || jLId.getText().equals(" ")) {
            query = sesion.createSQLQuery("SELECT*FROM ficha");
            query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
        } else {
            String ID = jLId.getText();
            query = sesion.createSQLQuery("SELECT*FROM ficha where idCliente = '" + ID + "' ");
            query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
        }

        java.util.List results = query.list();
        for (Object object : results) {
            Map row = (Map) object;
            tmResultSet.addRow(new Object[]{
                row.get("id"),
                row.get("matricula"),
                row.get("dataEntrada"),
                row.get("sexo"),
                row.get("peso"),
                row.get("altura"),
                row.get("idade"),
                row.get("frequenciaCardiaca"),
                row.get("frequenciaCardMaxima"),
                row.get("batimentos"),
                row.get("problemaSaude"),
                row.get("medicacao"),
                row.get("acompanhamento"),
                row.get("objetivo"),
                row.get("profissao"),
                row.get("idModeloFicha"),
                row.get("idCliente")
            //row.get("carga")
            });
        }
        jBAdicionar.setEnabled(true);

    }
 private void jTTabelaLinhaSelecionada(JTable tabela) {
        if (jTable1.getSelectedRow() != -1) {
          
            String cod = (jTable1.getValueAt(jTable1.getSelectedRow(), 0)).toString();
            this.idDescricaoControle = Integer.parseInt(cod);
            jLMatricula.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 1)).toString());
            jFDataEntrada.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 2)).toString());
            jCSexo.setSelectedItem((jTable1.getValueAt(jTable1.getSelectedRow(), 3)).toString());
            jTPeso.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 4)).toString());
            jTAltura.setText((jTable1.getValueAt(jTable1.getSelectedRow(), 5)).toString());
            jTIdade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jTFreqCard.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jTFreqCardM.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jTBatimentos.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            jCProbSaude.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
            jTMedicacao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
            jCAcompanhamento.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 12).toString());
            jTObjetivo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 13).toString());
            jTProfissao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 14).toString());
            jCModeloFicha.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 15).toString());
            jLabel20.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 16).toString());
 
            // jTMarca.setText(nomeMarca);
            jBAdicionar.setEnabled(false);
            //System.out.println(this.idDescricaoControle);
            
        }

    }

    private void editar() {
        Ficha ficha = new Ficha();
        ficha.setId(this.idDescricaoControle);
        ficha.setIdCliente(Integer.parseInt(jLId.getText()));
        ficha.setAcompanhamento(jCAcompanhamento.getSelectedItem().toString());
        ficha.setAltura(Float.parseFloat(jTAltura.getText()));
        ficha.setBatimentos(jTBatimentos.getText());
        ficha.setDataEntrada(jFDataEntrada.getText());
        ficha.setFrequenciaCardMaxima(Float.parseFloat(jTFreqCardM.getText()));
        ficha.setFrequenciaCardiaca(Float.parseFloat(jTFreqCard.getText()));
        ficha.setIdModeloFicha(Integer.parseInt(jCModeloFicha.getSelectedItem().toString()));
        ficha.setIdade(Integer.parseInt(jTIdade.getText()));
        ficha.setMatricula(jLMatricula.getText());
        ficha.setMedicacao(jTMedicacao.getText());
        ficha.setObjetivo(jTObjetivo.getText());
        ficha.setPeso(Float.parseFloat(jTPeso.getText()));
        ficha.setProblemaSaude(jCProbSaude.getSelectedItem().toString());
        ficha.setProfissao(jTProfissao.getText());
        ficha.setSexo(jCSexo.getSelectedItem().toString());

        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.update(ficha);
        session.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Alterado Com Sucesso.");
        
    }

    private void excluir() {
        Ficha ficha = new Ficha();
        ficha.setId(this.idDescricaoControle);
        ficha.setIdCliente(Integer.parseInt(jLId.getText()));
        ficha.setAcompanhamento(jCAcompanhamento.getSelectedItem().toString());
        ficha.setAltura(Float.parseFloat(jTAltura.getText()));
        ficha.setBatimentos(jTBatimentos.getText());
        ficha.setDataEntrada(jFDataEntrada.getText());
        ficha.setFrequenciaCardMaxima(Float.parseFloat(jTFreqCardM.getText()));
        ficha.setFrequenciaCardiaca(Float.parseFloat(jTFreqCard.getText()));
        ficha.setIdModeloFicha(Integer.parseInt(jCModeloFicha.getSelectedItem().toString()));
        ficha.setIdade(Integer.parseInt(jTIdade.getText()));
        ficha.setMatricula(jLMatricula.getText());
        ficha.setMedicacao(jTMedicacao.getText());
        ficha.setObjetivo(jTObjetivo.getText());
        ficha.setPeso(Float.parseFloat(jTPeso.getText()));
        ficha.setProblemaSaude(jCProbSaude.getSelectedItem().toString());
        ficha.setProfissao(jTProfissao.getText());
        ficha.setSexo(jCSexo.getSelectedItem().toString());

        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.delete(ficha);
        session.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Excluido Com Sucesso.");
    }

    private void pegaFicha() {
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        //PESQUISA COM SQLQUERY E JOIN MAIS TRANSFORMACAO EM LISTA DO HIBERNATE.
        SQLQuery query = sesion.createSQLQuery("select * from modeloficha");
        query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
        java.util.List results = query.list();
        for (Object object : results) {
            Map row = (Map) object;
            String idMF  = String.valueOf(row.get("id"));
            jCModeloFicha.addItem(idMF);
        }
    }
}
